import calendar
import tkinter
calendarr = calendar.calendar(2026)
ccreen = tkinter.Tk()
ccreen.title('Calendar')
ccreen.geometry('500x500')
label = tkinter.Label(ccreen, text = 'Enter the year', fg = 'black', bg = 'white' )
label.place(x = 250, y = 200)
entry = tkinter.Entry(ccreen, fg = 'black', bg = 'white')
entry.place(x = 250, y = 250)
def click():
    year = entry.get()
    newscreen = tkinter.Tk()
    newscreen.title = ('Calendar')
    newscreen.geometry('700x700')
    clndrlbl = tkinter.Text(newscreen)
    clndrlbl.place(x = 0, y = 0)
    clndrlbl.insert('1.0', calendar.calendar(int(year)))
button = tkinter.Button(ccreen, text = 'Confirm', fg = 'black', bg = 'white', command = click)
button.place(x = 250, y = 300)
ccreen.mainloop()